{{- if and .Values.keycloak.enabled .Values.keycloak.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.keycloak.service.name }}-ingress
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    {{- include "deployment.keycloak.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.keycloak.ingress.annotations }}
    {{- toYaml .Values.keycloak.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.keycloak.ingress.middlewares }}
    traefik.ingress.kubernetes.io/middlewares: {{ .Values.keycloak.ingress.middlewares | join "," }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.keycloak.ingress.className | default "traefik" }}
  {{- if and .Values.keycloak.ingress.tls.enabled .Values.keycloak.ingress.tls.secretName }}
  tls:
    - hosts:
        - {{ .Values.keycloak.ingress.host | quote }}
      secretName: {{ .Values.keycloak.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.keycloak.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.keycloak.ingress.path | default "/" }}
        pathType: {{ .Values.keycloak.ingress.pathType | default "Prefix" }}
        backend:
          service:
            name: {{ .Values.keycloak.service.name }}
            port:
              number: {{ .Values.keycloak.service.port | default 8080 }}
{{- end }}

