---
# Source: deployment/templates/keycloak-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-service-ingress
  namespace: keycloak
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: keycloak-service
    app.kubernetes.io/instance: app-deployment
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    traefik.ingress.kubernetes.io/entrypoints: web
    traefik.ingress.kubernetes.io/forward-auth-headers: "true"
    traefik.ingress.kubernetes.io/redirect-to-https: "false"
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
spec:
  ingressClassName: traefik
  rules:
  - host: "keycloak.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080
